#!/usr/bin/env python3
"""
fit_allegro.py
==============
Fit an Allegro E(3)-equivariant interatomic potential to the
strained bilayer graphene rVV10 dataset, then generate a parity plot.

Usage
-----
python fit_allegro.py
python fit_allegro.py --epochs 200 --output-dir allegro_blg
python fit_allegro.py --xyz ../../data/strained_bilayer_graphene_rVV10.xyz

Model architecture ("core") hyperparameters can be set on the CLI, e.g. a
larger model:
python fit_allegro.py --l-max 2 --num-layers 2 --num-scalar-features 32 \
    --num-tensor-features 16 --num-bessels 8 --lr 0.002 --output-dir allegro_big
Run ``python fit_allegro.py --help`` for the full list.

Requirements
------------
conda env allegro_env  (nequip 0.18, allegro 0.8, torch 2.x)
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import textwrap
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_XYZ = HERE.parent.parent / "data" / "strained_bilayer_graphene_rVV10.xyz"
DEFAULT_OUT = HERE / "allegro_blg_output"
# Total frames in the dataset (972 for strained_bilayer_graphene_rVV10.xyz).
# Adjust if you use a different dataset.
_DATASET_TOTAL = 972


# ---------------------------------------------------------------------------
# Env check
# ---------------------------------------------------------------------------

def _ensure_allegro() -> None:
    missing = []
    for pkg in ("nequip", "allegro"):
        try:
            __import__(pkg)
        except ImportError:
            missing.append(pkg)
    if not missing:
        return
    print(
        f"Required packages not found: {missing}\n"
        "Install with:  pip install nequip-allegro\n"
        "Attempting install now …",
        flush=True,
    )
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "nequip-allegro"],
        stdout=sys.stdout,
        stderr=sys.stderr,
    )
    for pkg in missing:
        try:
            __import__(pkg)
        except ImportError:
            sys.exit(
                f"ERROR: '{pkg}' still not importable after pip install.\n"
                "Please install manually: pip install nequip-allegro"
            )


# ---------------------------------------------------------------------------
# Config (nequip 0.18 / allegro 0.8 format)
# ---------------------------------------------------------------------------

def _write_config(
    config_path: Path,
    xyz_path: Path,
    output_dir: Path,
    n_train: int,
    n_val: int,
    n_test: int,
    epochs: int,
    r_max: float,
    seed: int,
    *,
    l_max: int = 1,
    parity: bool = True,
    num_layers: int = 1,
    num_scalar_features: int = 8,
    num_tensor_features: int = 8,
    num_bessels: int = 8,
    polynomial_cutoff_p: int = 6,
    bessel_trainable: bool = False,
    mlp_width: int | None = None,
    readout_mlp_width: int | None = None,
    lr: float = 0.001,
    batch_size: int = 4,
) -> None:
    """Write a minimal Allegro config compatible with nequip 0.18 + allegro 0.8.

    The keyword-only arguments expose the Allegro **model architecture
    hyperparameters** (the "core hyperparameters" block) so they can be set
    from the command line.  ``mlp_width`` / ``readout_mlp_width`` default to
    ``num_scalar_features`` when left unset.
    """
    # YAML booleans must be lowercase; widths default to num_scalar_features.
    parity_str = "true" if parity else "false"
    bessel_trainable_str = "true" if bessel_trainable else "false"
    mlp_width_val = num_scalar_features if mlp_width is None else int(mlp_width)
    readout_width_val = (
        num_scalar_features if readout_mlp_width is None else int(readout_mlp_width)
    )
    cfg = textwrap.dedent(f"""\
        # Allegro config — strained bilayer graphene (rVV10)
        # Auto-generated by fit_allegro.py  (nequip 0.18 / allegro 0.8)

        run: [train, test]

        seed: {seed}
        cutoff_radius: {r_max}
        model_type_names: [C]

        # --------------- data ---------------
        data:
          _target_: nequip.data.datamodule.ASEDataModule
          seed: ${{seed}}
          # Single extxyz file — split into train / val / test
          split_dataset:
            - file_path: {xyz_path.as_posix()}
              train: {n_train}
              val: {n_val}
              test: {n_test}
          transforms:
            - _target_: nequip.data.transforms.ChemicalSpeciesToAtomTypeMapper
              model_type_names: ${{model_type_names}}
              chemical_species_to_atom_type_map:
                C: C
            - _target_: nequip.data.transforms.NeighborListTransform
              r_max: ${{cutoff_radius}}
          train_dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: {batch_size}
          val_dataloader:
            _target_: torch.utils.data.DataLoader
            batch_size: 8
          test_dataloader: ${{data.val_dataloader}}
          stats_manager:
            _target_: nequip.data.CommonDataStatisticsManager
            type_names: ${{model_type_names}}

        # --------------- trainer ---------------
        trainer:
          _target_: lightning.Trainer
          max_epochs: {epochs}
          check_val_every_n_epoch: 1
          log_every_n_steps: 10
          logger:
            _target_: lightning.pytorch.loggers.CSVLogger
            save_dir: ${{hydra:runtime.output_dir}}
            name: ""
            version: 0
          callbacks:
            - _target_: lightning.pytorch.callbacks.ModelCheckpoint
              monitor: val0_epoch/weighted_sum
              mode: min
              dirpath: ${{hydra:runtime.output_dir}}
              filename: best
              save_last: true
            - _target_: nequip.train.callbacks.TestTimeXYZFileWriter
              out_file: ${{hydra:runtime.output_dir}}/test_predictions
              output_fields_from_original_dataset: [total_energy, forces]
              chemical_symbols: [C]
            - _target_: nequip.train.callbacks.LossCoefficientMonitor
              interval: epoch
              frequency: 10

        # --------------- training module ---------------
        # Model size scales with num_scalar_features / num_tensor_features /
        # num_layers / l_max (num_scalar_features=8 ⇒ ~1760 trainable params).
        num_scalar_features: {num_scalar_features}

        training_module:
          _target_: nequip.train.EMALightningModule
          loss:
            _target_: nequip.train.EnergyForceLoss
            per_atom_energy: true
            coeffs:
              total_energy: 1.0
              forces: 1.0
          val_metrics:
            _target_: nequip.train.EnergyForceMetrics
            coeffs:
              total_energy_mae: 1.0
              forces_mae: 1.0
          test_metrics: ${{training_module.val_metrics}}
          optimizer:
            _target_: torch.optim.Adam
            lr: {lr}

          model:
            _target_: allegro.model.AllegroModel

            seed: {seed}
            model_dtype: float32
            type_names: ${{model_type_names}}
            r_max: ${{cutoff_radius}}

            # ── two-body radial-chemical embedding ──
            radial_chemical_embed:
              _target_: allegro.nn.TwoBodyBesselScalarEmbed
              num_bessels: {num_bessels}
              bessel_trainable: {bessel_trainable_str}
              polynomial_cutoff_p: {polynomial_cutoff_p}

            # ── core hyperparameters (minimal) ──
            l_max: {l_max}
            parity: {parity_str}
            num_layers: {num_layers}
            num_scalar_features: ${{num_scalar_features}}
            num_tensor_features: {num_tensor_features}

            # ── MLP widths ──
            allegro_mlp_hidden_layers_width: {mlp_width_val}
            readout_mlp_hidden_layers_width: {readout_width_val}

            # ── per-type normalisation (derived from training statistics) ──
            avg_num_neighbors: ${{training_data_stats:per_type_num_neighbors_mean}}
            per_type_energy_shifts: ${{training_data_stats:per_atom_energy_mean}}
            per_type_energy_scales: ${{training_data_stats:per_type_forces_rms}}
    """)
    config_path.write_text(cfg)
    print(f"Config written to {config_path}", flush=True)


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def _run_training(config_path: Path, output_dir: Path) -> None:
    """Invoke nequip 0.18 train via Hydra CLI."""
    # Hydra resolves config_path at import time as os.getcwd(), but we can
    # override it with --config-path.  The config file must be named
    # config.yaml (matching --config-name config).
    cmd = [
        sys.executable, "-m", "nequip.scripts.train",
        f"--config-path={output_dir.as_posix()}",
        "--config-name=config",
        f"hydra.run.dir={output_dir.as_posix()}",
    ]
    print(f"\nRunning: {' '.join(cmd)}\n", flush=True)
    subprocess.check_call(cmd)


# ---------------------------------------------------------------------------
# Parity plot (reads TestTimeXYZFileWriter output)
# ---------------------------------------------------------------------------

def _parity_plot(output_dir: Path) -> None:
    import numpy as np
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from ase.io import read as ase_read

    print("\nGenerating parity plot …", flush=True)

    # TestTimeXYZFileWriter writes {out_file}_dataset{idx}.xyz
    test_file = output_dir / "test_predictions_dataset0.xyz"
    if not test_file.exists():
        # Fallback: look for any epoch-suffixed variant
        candidates = sorted(output_dir.glob("test_predictions*dataset0*.xyz"))
        if not candidates:
            print("WARNING: No test predictions file found; skipping parity plot.",
                  file=sys.stderr)
            print(f"  (looked for: {test_file})", file=sys.stderr)
            return
        test_file = candidates[-1]

    frames = ase_read(str(test_file), index=":")
    if not frames:
        print("WARNING: Test predictions file is empty.", file=sys.stderr)
        return

    # Predicted energy is stored as the ASE calculator energy;
    # ground-truth energy is stored as original_dataset_energy (nequip maps
    # total_energy -> energy for ASE compatibility).
    e_pred = np.array([f.get_potential_energy() for f in frames])
    e_ref  = np.array([f.info["original_dataset_energy"] for f in frames])
    n_atoms = np.array([len(f) for f in frames])

    e_pred_pa = e_pred / n_atoms
    e_ref_pa  = e_ref  / n_atoms

    mae  = float(np.mean(np.abs(e_pred_pa - e_ref_pa)))
    rmse = float(np.sqrt(np.mean((e_pred_pa - e_ref_pa) ** 2)))

    fig, ax = plt.subplots(figsize=(6, 6))
    ax.scatter(
        e_ref_pa, e_pred_pa,
        s=8, alpha=0.5, color="steelblue", linewidths=0,
        label=f"MAE  = {mae*1000:.2f} meV/atom\nRMSE = {rmse*1000:.2f} meV/atom",
    )
    lo = min(e_ref_pa.min(), e_pred_pa.min())
    hi = max(e_ref_pa.max(), e_pred_pa.max())
    ax.plot([lo, hi], [lo, hi], "k--", lw=0.8, label="ideal")
    ax.set_xlabel("DFT energy (eV/atom)", fontsize=12)
    ax.set_ylabel("Allegro energy (eV/atom)", fontsize=12)
    ax.set_title("Allegro — strained bilayer graphene (rVV10)", fontsize=11)
    ax.legend(fontsize=10)
    fig.tight_layout()

    output_dir.mkdir(parents=True, exist_ok=True)
    out = output_dir / "parity_energy_per_atom.png"
    fig.savefig(str(out), dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Parity plot saved to {out}", flush=True)
    print(f"  MAE  = {mae*1000:.3f} meV/atom", flush=True)
    print(f"  RMSE = {rmse*1000:.3f} meV/atom", flush=True)


# ---------------------------------------------------------------------------
# Loss curve (reads CSVLogger metrics.csv)
# ---------------------------------------------------------------------------

def _loss_curve_plot(output_dir: Path) -> None:
    import csv
    import numpy as np
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    print("\nGenerating loss curve …", flush=True)

    # CSVLogger writes to {output_dir}/version_0/metrics.csv
    candidates = sorted(output_dir.glob("**/metrics.csv"))
    if not candidates:
        print("WARNING: No metrics.csv found; skipping loss curve.", file=sys.stderr)
        return
    csv_path = candidates[0]

    # Parse the CSV manually (avoids pandas dependency)
    rows: list[dict] = []
    with open(csv_path, newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            rows.append(row)

    if not rows:
        print("WARNING: metrics.csv is empty; skipping loss curve.", file=sys.stderr)
        return

    def _col(name: str) -> tuple[np.ndarray, np.ndarray]:
        """Return (epoch, value) arrays for rows where `name` is non-empty."""
        epochs, vals = [], []
        for r in rows:
            if r.get(name, "").strip():
                try:
                    epochs.append(float(r["epoch"]))
                    vals.append(float(r[name]))
                except (KeyError, ValueError):
                    pass
        return np.array(epochs), np.array(vals)

    # nequip logs per-step training metrics and per-epoch validation metrics.
    # Average per-step values within each epoch for a smooth train curve.
    def _epoch_mean(name: str) -> tuple[np.ndarray, np.ndarray]:
        ep_raw, v_raw = _col(name)
        if ep_raw.size == 0:
            return np.array([]), np.array([])
        epochs_u = np.unique(ep_raw)
        means = np.array([v_raw[ep_raw == e].mean() for e in epochs_u])
        return epochs_u, means

    fig, axes = plt.subplots(1, 2, figsize=(11, 4), constrained_layout=True)

    # nequip logs epoch-level training as train_loss_epoch/...
    # and validation as val0_epoch/...  (MAE-based metrics)

    # ── combined weighted-sum loss ──
    ax = axes[0]
    te, tv = _col("train_loss_epoch/weighted_sum")
    ve, vv = _col("val0_epoch/weighted_sum")
    if te.size:
        ax.semilogy(te, tv, color="steelblue", lw=1.5, label="train")
    if ve.size:
        ax.semilogy(ve, vv, color="tomato", lw=1.5, label="val")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Weighted loss")
    ax.set_title("Loss (weighted sum) vs epoch")
    ax.legend()

    # ── per-atom energy MAE and forces MAE (validation) ──
    ax = axes[1]
    ee, ev = _col("val0_epoch/per_atom_energy_mae")
    fe, fv = _col("val0_epoch/forces_mae")
    if ee.size:
        ax.semilogy(ee, ev * 1e3, color="steelblue", lw=1.5, label="energy MAE (meV/atom)")
    if fe.size:
        ax.semilogy(fe, fv, color="tomato", lw=1.5, label="forces MAE (eV/Å)")
    ax.set_xlabel("Epoch")
    ax.set_title("Validation MAE vs epoch")
    ax.legend()

    fig.suptitle("Allegro — strained bilayer graphene (rVV10)", fontsize=11)

    out = output_dir / "loss_curve.png"
    fig.savefig(str(out), dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Loss curve saved to {out}", flush=True)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(
        description="Fit an Allegro potential to strained bilayer graphene.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("--xyz", type=Path, default=DEFAULT_XYZ,
                   help=f"Path to extxyz dataset (default: {DEFAULT_XYZ})")
    p.add_argument("--output-dir", type=Path, default=DEFAULT_OUT,
                   help=f"Output directory (default: {DEFAULT_OUT})")
    p.add_argument("--epochs", type=int, default=100,
                   help="Training epochs (default: 100)")
    p.add_argument("--r-max", type=float, default=6.0,
                   help="Cutoff radius in Å (default: 6.0)")
    p.add_argument("--n-train", type=int, default=700,
                   help="Training frames (default: 700)")
    p.add_argument("--n-val", type=int, default=150,
                   help="Validation frames (default: 150)")
    p.add_argument("--seed", type=int, default=42)

    # ── Allegro model architecture ("core") hyperparameters ──
    mh = p.add_argument_group("Allegro model hyperparameters")
    mh.add_argument("--l-max", type=int, default=1,
                    help="Max rotation order l of tensor features (default: 1).")
    mh.add_argument("--num-layers", type=int, default=1,
                    help="Number of Allegro tensor-product layers (default: 1).")
    mh.add_argument("--num-scalar-features", type=int, default=8,
                    help="Scalar feature width; drives model size (default: 8).")
    mh.add_argument("--num-tensor-features", type=int, default=8,
                    help="Number of equivariant tensor features (default: 8).")
    mh.add_argument("--parity", action=argparse.BooleanOptionalAction, default=True,
                    help="Include parity (odd) features (default: --parity).")
    mh.add_argument("--num-bessels", type=int, default=8,
                    help="Bessel radial basis functions in two-body embed (default: 8).")
    mh.add_argument("--polynomial-cutoff-p", type=int, default=6,
                    help="Polynomial envelope power p for the cutoff (default: 6).")
    mh.add_argument("--bessel-trainable", action=argparse.BooleanOptionalAction,
                    default=False, help="Train the Bessel frequencies (default: off).")
    mh.add_argument("--mlp-width", type=int, default=None,
                    help="Allegro MLP hidden width (default: num_scalar_features).")
    mh.add_argument("--readout-mlp-width", type=int, default=None,
                    help="Readout MLP hidden width (default: num_scalar_features).")
    mh.add_argument("--lr", type=float, default=0.001,
                    help="Adam learning rate (default: 0.001).")
    mh.add_argument("--batch-size", type=int, default=4,
                    help="Training batch size (default: 4).")

    p.add_argument("--plot-only", action="store_true",
                   help="Skip training; read existing test predictions and plot.")
    args = p.parse_args()

    xyz_path = args.xyz.resolve()
    if not args.plot_only and not xyz_path.is_file():
        p.error(f"Dataset not found: {xyz_path}")

    _ensure_allegro()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    # The config file must be named 'config.yaml' to match --config-name=config
    config_path = args.output_dir / "config.yaml"

    n_test = _DATASET_TOTAL - args.n_train - args.n_val
    if n_test <= 0:
        p.error(
            f"n_train ({args.n_train}) + n_val ({args.n_val}) "
            f">= dataset size ({_DATASET_TOTAL}). Reduce --n-train or --n-val."
        )

    if not args.plot_only:
        _write_config(
            config_path,
            xyz_path,
            args.output_dir.resolve(),
            n_train=args.n_train,
            n_val=args.n_val,
            n_test=n_test,
            epochs=args.epochs,
            r_max=args.r_max,
            seed=args.seed,
            l_max=args.l_max,
            parity=args.parity,
            num_layers=args.num_layers,
            num_scalar_features=args.num_scalar_features,
            num_tensor_features=args.num_tensor_features,
            num_bessels=args.num_bessels,
            polynomial_cutoff_p=args.polynomial_cutoff_p,
            bessel_trainable=args.bessel_trainable,
            mlp_width=args.mlp_width,
            readout_mlp_width=args.readout_mlp_width,
            lr=args.lr,
            batch_size=args.batch_size,
        )
        _run_training(config_path, args.output_dir.resolve())

    _parity_plot(args.output_dir.resolve())
    _loss_curve_plot(args.output_dir.resolve())


if __name__ == "__main__":
    main()
