#!/usr/bin/env python3
"""
Equilibrium interlayer separation vs in-plane strain (AB and AA stacking).

Equilibrium in-plane lattice constant reference: ``LAT_CON = 2.4694`` Å (see
:mod:`blg_model_builder.strain_data`).

DFT reference: single-point energies in ``data/blg_poisson_ratio_structures.xyz``
(generated by ``DD-TETB/generate_data/gen_training_data_structures.py``).  At each
stacking and uniaxial strain along lattice vector 1 (``dy = 0``), a quadratic
``E(d)`` is fit to the five sampled interlayer separations; the vertex gives
``d_eq(ε)``.

Model ensemble: total energies on the same structures for each MCMC draw;
``d_eq(ε)`` is extracted the same way.  Plots show ensemble mean ± std with DFT
overlay.  At the end, prints the out-of-plane Poisson ratio
``ν = −d(d_eq)/dε|_{ε=0}`` for DFT and ensemble (mean ± std).

Output:

* ``figures/<model>_<stacking>_poisson_layer_sep.png`` — equilibrium separation vs strain
* ``figures/<model>_<stacking>_poisson_ratio_histogram.png`` — ensemble ν histogram with DFT line
* ``figures/DFT_<stacking>_poisson_energy_vs_sep.png`` — DFT energy vs separation PES

Examples
--------
::

    python visualizations/plot_poisson_ratio.py --models POD_energy
    python visualizations/plot_poisson_ratio.py \\
        --models 'POD_energy_POD_index*' --n-samples 50 --temperature 0.5

With no ``--models``, uses the ``POD_energy_POD_index*`` ensemble with the lowest
NLL on the saved calibration grid (temperature at minimum miscalibration area).
"""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import ase.io
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import numpy as np
from ase import Atoms
from matplotlib.colors import Normalize

CSFONT = {"fontname": "sans-serif", "size": 20}
plt.rcParams.update(
    {
        "font.family": CSFONT["fontname"],
        "font.size": CSFONT["size"],
        "axes.labelsize": CSFONT["size"],
        "axes.titlesize": CSFONT["size"],
        "legend.fontsize": 12,
        "xtick.labelsize": CSFONT["size"],
        "ytick.labelsize": CSFONT["size"],
    }
)

# Side effect: ``Atoms.relax_structure`` patch (Allegro / LAMMPS helpers).
from blg_model_builder.potentials import PODASECalculator  # noqa: F401

from blg_model_builder.ensemble_io import (
    DEFAULT_CALIBRATION_METRICS_DIR,
    expand_model_patterns,
    load_ensemble_pickle,
    load_metrics_npz,
    metrics_npz_path,
    resolve_ensemble_pickle,
)
from blg_model_builder.cli_hyperparams import add_hyperparam_args
from blg_model_builder.cli_model_names import (
    add_energy_models_arg,
    collect_workflow_hyperparams,
)
from blg_model_builder.strain_data import (
    LAT_CON,
    cell_strains,
    identify_stacking,
    interlayer_sep,
    layers_have_uniform_z,
)

HERE = Path(__file__).resolve().parent
UQ_DIR = HERE.parent
REPO_ROOT = UQ_DIR.parent

_uq_dir = str(UQ_DIR)
if _uq_dir not in sys.path:
    sys.path.insert(0, _uq_dir)

from uq_model_runtime import (  # noqa: E402
    apply_uq_parameters,
    build_uq_calculator,
    is_uq_energy_model,
)

DEFAULT_FIGURES_DIR = UQ_DIR / "figures"
DEFAULT_DFT_XYZ = REPO_ROOT / "data" / "blg_poisson_ratio_structures.xyz"
DEFAULT_ENSEMBLE_DIR = "ensembles"

# ``gen_training_data_structures.py`` Poisson-ratio block (uniaxial along a1).
STRAIN_GRID = np.array([-0.01, -0.005, 0.0, 0.005, 0.01], dtype=float)
STRAIN_DY = 0.0
CROSS_STRAIN_ATOL = 0.003
STRAIN_DECIMALS = 5
N_LOCAL_QUAD = 5
STACKINGS = ("AB", "AA")

DEFAULT_N_SAMPLES = 500
DEFAULT_ENSEMBLE_SHUFFLE_SEED = 0
DEFAULT_POLY_DEGREE = 2

# Equilibrium in-plane lattice constant (Å); ``cell_strains`` divides by this value.
REF_LAT_CON = LAT_CON


@dataclass(frozen=True)
class PoissonFrame:
    atoms: Atoms
    stacking: str
    dx: float
    dy: float
    separation: float
    dft_energy: float


@dataclass(frozen=True)
class StrainSepPoint:
    stacking: str
    dx: float
    dy: float
    separation: float


def _shuffle_ensemble(ensemble: np.ndarray, seed: int) -> np.ndarray:
    ensemble = np.asarray(ensemble, dtype=float)
    if ensemble.ndim != 2:
        raise ValueError(f"Expected 2-D ensemble array, got shape {ensemble.shape}")
    order = np.random.default_rng(seed).permutation(ensemble.shape[0])
    return ensemble[order]


def _is_lammps_error(exc: BaseException) -> bool:
    cur: Optional[BaseException] = exc
    seen: set[int] = set()
    while cur is not None and id(cur) not in seen:
        seen.add(id(cur))
        if "lammps" in type(cur).__module__.lower():
            return True
        msg = str(cur).lower()
        if "lammps" in msg or "lmp_" in msg:
            return True
        cur = cur.__cause__ if cur.__cause__ is not None else cur.__context__
    if isinstance(exc, RuntimeError):
        msg = str(exc).lower()
        if "lammps" in msg or "relax_structure" in msg:
            return True
    return False


def _match_strain(values: np.ndarray, target: float, decimals: int = STRAIN_DECIMALS) -> np.ndarray:
    return np.isclose(values, float(target), atol=10.0 ** (-decimals))


def equilibrium_sep_quadratic(
    sep: np.ndarray,
    energy: np.ndarray,
    n_local: int = N_LOCAL_QUAD,
) -> float:
    """
    Equilibrium interlayer separation from ``E(sep)``.

    Fit a quadratic to the ``n_local`` lowest-energy points (all five when the
    slice has exactly five separations) and return the parabolic minimum.
    """
    sep = np.asarray(sep, dtype=float).ravel()
    energy = np.asarray(energy, dtype=float).ravel()
    m = np.isfinite(sep) & np.isfinite(energy)
    sep, energy = sep[m], energy[m]
    if sep.size < 3:
        return float(sep[np.argmin(energy)]) if sep.size else float("nan")
    order = np.argsort(energy)
    n_use = min(int(n_local), sep.size)
    ix = order[:n_use]
    xs = sep[ix]
    ys = energy[ix]
    j = np.argsort(xs)
    xs, ys = xs[j], ys[j]
    try:
        xc = xs - np.mean(xs)
        a2, a1, _a0 = np.polyfit(xc, ys, 2, rcond=None)
        d_min = float(np.mean(xs) - 0.5 * a1 / a2)
    except np.linalg.LinAlgError:
        return float(xs[np.argmin(ys)])
    if a2 <= 0:
        return float(xs[np.argmin(ys)])
    if d_min < xs.min() or d_min > xs.max():
        return float(xs[np.argmin(ys)])
    return d_min


def fit_quadratic_energy_curve(
    sep: np.ndarray,
    energy: np.ndarray,
) -> Tuple[np.ndarray, float, float]:
    """
    Quadratic least-squares fit ``E(d)`` through all points at one strain.

    Returns ``(coeffs, d_eq, e_eq)`` where ``coeffs`` are ``np.polyval`` order
    (highest degree first) and ``(d_eq, e_eq)`` is the parabolic minimum.
    """
    sep = np.asarray(sep, dtype=float).ravel()
    energy = np.asarray(energy, dtype=float).ravel()
    m = np.isfinite(sep) & np.isfinite(energy)
    sep, energy = sep[m], energy[m]
    if sep.size == 0:
        return np.array([np.nan, np.nan, np.nan]), float("nan"), float("nan")
    if sep.size < 3:
        j = int(np.argmin(energy))
        return np.array([0.0, 0.0, float(energy[j])]), float(sep[j]), float(energy[j])

    order = np.argsort(sep)
    xs, ys = sep[order], energy[order]
    try:
        coeffs = np.polyfit(xs, ys, 2)
    except np.linalg.LinAlgError:
        j = int(np.argmin(ys))
        return np.array([0.0, 0.0, float(ys[j])]), float(xs[j]), float(ys[j])

    a2, a1 = float(coeffs[0]), float(coeffs[1])
    if abs(a2) < 1e-18 or a2 <= 0.0:
        j = int(np.argmin(ys))
        d_eq = float(xs[j])
    else:
        d_eq = float(-0.5 * a1 / a2)
        if d_eq < xs.min() or d_eq > xs.max():
            j = int(np.argmin(ys))
            d_eq = float(xs[j])
    e_eq = float(np.polyval(coeffs, d_eq))
    return coeffs, d_eq, e_eq


def _frames_at_strain(
    frames: Sequence[PoissonFrame],
    stacking: str,
    target_dx: float,
) -> List[PoissonFrame]:
    return [
        f for f in frames
        if f.stacking == stacking and _match_strain(np.array([f.dx]), float(target_dx))[0]
    ]


def load_poisson_frames(xyz_path: Path) -> List[PoissonFrame]:
    """Load DFT single-point Poisson-ratio structures from an extxyz file."""
    if not xyz_path.is_file():
        raise FileNotFoundError(f"DFT reference not found: {xyz_path}")

    frames: List[PoissonFrame] = []
    n_skip_dy = 0
    n_skip_z = 0
    for atoms in ase.io.read(str(xyz_path), index=":"):
        if not layers_have_uniform_z(atoms):
            n_skip_z += 1
            continue
        stack = identify_stacking(atoms)
        if stack not in STACKINGS:
            continue
        dx, dy = cell_strains(atoms)
        if abs(float(dy)) > CROSS_STRAIN_ATOL:
            n_skip_dy += 1
            continue
        frames.append(
            PoissonFrame(
                atoms=atoms,
                stacking=stack,
                dx=float(dx),
                dy=float(dy),
                separation=float(interlayer_sep(atoms)),
                dft_energy=float(atoms.get_potential_energy()),
            )
        )

    if n_skip_z:
        print(f"  skipped {n_skip_z} frame(s) with non-uniform layer z", flush=True)
    if n_skip_dy:
        print(f"  skipped {n_skip_dy} frame(s) with dy != 0", flush=True)
    return frames


def _strain_values_for_stacking(frames: Sequence[PoissonFrame], stacking: str) -> np.ndarray:
    dx = np.array([f.dx for f in frames if f.stacking == stacking], dtype=float)
    if dx.size == 0:
        return np.array([], dtype=float)
    rounded = np.round(dx, STRAIN_DECIMALS)
    return np.sort(np.unique(rounded))


def d_eq_vs_strain_from_energies(
    frames: Sequence[PoissonFrame],
    stacking: str,
    energies: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return ``(strains, d_eq)`` from total energies aligned with ``frames``."""
    energies = np.asarray(energies, dtype=float).ravel()
    if energies.size != len(frames):
        raise ValueError(
            f"Expected {len(frames)} energies, got {energies.size}"
        )

    sub = [(i, f) for i, f in enumerate(frames) if f.stacking == stacking]
    strains = _strain_values_for_stacking(frames, stacking)
    d_eq = np.full(strains.size, np.nan, dtype=float)

    for k, target_dx in enumerate(strains):
        block = [
            (f.separation, energies[i])
            for i, f in sub
            if _match_strain(np.array([f.dx]), float(target_dx))[0]
        ]
        if len(block) < 3:
            continue
        seps, ens = zip(*block)
        d_eq[k] = equilibrium_sep_quadratic(np.asarray(seps), np.asarray(ens))

    return strains, d_eq


def dft_equilibrium_path(
    frames: Sequence[PoissonFrame],
    stacking: str,
) -> Tuple[np.ndarray, np.ndarray, List[StrainSepPoint]]:
    """DFT ``d_eq(ε)`` and points for plotting."""
    dft_energies = np.array([f.dft_energy for f in frames], dtype=float)
    strains, d_eq = d_eq_vs_strain_from_energies(frames, stacking, dft_energies)
    points = [
        StrainSepPoint(stacking=stacking, dx=float(s), dy=STRAIN_DY, separation=float(d))
        for s, d in zip(strains, d_eq)
        if np.isfinite(d)
    ]
    return strains, d_eq, points


def poisson_ratio_at_zero(
    strains: np.ndarray,
    d_eq: np.ndarray,
    poly_degree: int = DEFAULT_POLY_DEGREE,
) -> float:
    """Out-of-plane Poisson ratio ν = −d(d_eq)/dε evaluated at ε = 0."""
    eps = np.asarray(strains, dtype=float).ravel()
    d = np.asarray(d_eq, dtype=float).ravel()
    m = np.isfinite(eps) & np.isfinite(d)
    eps, d = eps[m], d[m]
    if eps.size < 2:
        return float("nan")
    deg = min(int(poly_degree), int(eps.size) - 1)
    p = np.polyfit(eps, d, deg)
    return -float(np.polyval(np.polyder(p), 0.0))


def poisson_ratio_ensemble_samples(
    strains: np.ndarray,
    sep_ensemble: np.ndarray,
    poly_degree: int = DEFAULT_POLY_DEGREE,
) -> np.ndarray:
    """Per-ensemble-member Poisson ratios ``ν = −d(d_eq)/dε`` at ε = 0."""
    sep_ensemble = np.asarray(sep_ensemble, dtype=float)
    if sep_ensemble.ndim != 2 or sep_ensemble.shape[1] == 0:
        return np.array([], dtype=float)
    return np.array(
        [
            poisson_ratio_at_zero(strains, sep_ensemble[:, j], poly_degree)
            for j in range(sep_ensemble.shape[1])
        ],
        dtype=float,
    )


def poisson_ratio_ensemble_stats(
    strains: np.ndarray,
    sep_ensemble: np.ndarray,
    poly_degree: int = DEFAULT_POLY_DEGREE,
) -> Tuple[float, float]:
    """Mean and standard deviation of ν over successful ensemble members."""
    nu_samples = poisson_ratio_ensemble_samples(strains, sep_ensemble, poly_degree)
    ok = np.isfinite(nu_samples)
    if not np.any(ok):
        return float("nan"), float("nan")
    return float(np.mean(nu_samples[ok])), float(np.std(nu_samples[ok]))


def evaluate_ensemble_vs_strain(
    calc_obj,
    ensemble_shuffled: np.ndarray,
    n_samples: int,
    stacking: str,
    frames: Sequence[PoissonFrame],
    *,
    set_params_fn=None,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, int]:
    """
    Evaluate total energies on all Poisson structures; extract ``d_eq(ε)`` per draw.

    Returns ``(strain_grid, mean_sep, std_sep, sep_ensemble, n_success)`` where
    ``sep_ensemble`` has shape ``(n_strain, n_success)``.
    """
    sub_indices = [i for i, f in enumerate(frames) if f.stacking == stacking]
    if not sub_indices:
        return np.array([]), np.array([]), np.array([]), np.zeros((0, 0)), 0

    atoms_list = [frames[i].atoms for i in sub_indices]
    strain_grid = _strain_values_for_stacking(frames, stacking)
    n_strain = strain_grid.size
    sep_ensemble = np.full((n_strain, n_samples), np.nan, dtype=float)
    n_success = 0

    calc_obj.prepare_batch(atoms_list)

    for theta in ensemble_shuffled:
        if n_success >= n_samples:
            break
        try:
            apply_uq_parameters(calc_obj, theta, set_params_fn)
            energies_sub, _ = calc_obj.evaluate_batch()
            energies_sub = np.asarray(energies_sub, dtype=float).ravel()
            if energies_sub.size != len(sub_indices) or not np.all(np.isfinite(energies_sub)):
                continue

            energies_full = np.full(len(frames), np.nan, dtype=float)
            for j, frame_idx in enumerate(sub_indices):
                energies_full[frame_idx] = energies_sub[j]

            _, d_eq = d_eq_vs_strain_from_energies(frames, stacking, energies_full)
            if not np.all(np.isfinite(d_eq)):
                continue

            sep_ensemble[:, n_success] = d_eq
            n_success += 1
        except Exception as exc:
            if _is_lammps_error(exc):
                print(f"    skip ensemble member (LAMMPS): {exc}", file=sys.stderr)
            else:
                print(f"    skip ensemble member: {exc}", file=sys.stderr)
            continue

    if n_success:
        mean_sep = np.nanmean(sep_ensemble[:, :n_success], axis=1)
        std_sep = np.nanstd(sep_ensemble[:, :n_success], axis=1)
        sep_out = sep_ensemble[:, :n_success].copy()
    else:
        mean_sep = np.full(n_strain, np.nan)
        std_sep = np.full(n_strain, np.nan)
        sep_out = np.zeros((n_strain, 0), dtype=float)
    return strain_grid, mean_sep, std_sep, sep_out, n_success


def select_pod_model_lowest_nll(
    ensemble_dir: str,
    calibration_metrics_dir: str,
    *,
    calibration_technique: str = "mcmc",
    calibration_target: str = "energy",
) -> str:
    """Return the ``POD_energy_POD_index*`` folder with minimum calibration NLL."""
    candidates = expand_model_patterns(["POD_energy_POD_index*"], ensemble_dir)
    best_name: Optional[str] = None
    best_nll = float("inf")
    for model_name in candidates:
        path = metrics_npz_path(
            calibration_metrics_dir, model_name, calibration_technique, calibration_target,
        )
        if not os.path.isfile(path):
            continue
        nll_arr = np.asarray(load_metrics_npz(path)["nll"], dtype=float)
        nll_min = float(np.nanmin(nll_arr)) if nll_arr.size else float("nan")
        if np.isfinite(nll_min) and nll_min < best_nll:
            best_nll = nll_min
            best_name = model_name
    if best_name is None:
        raise ValueError(
            "No POD_energy_POD_index* model with finite calibration NLL found under "
            f"{ensemble_dir!r} / {calibration_metrics_dir!r}."
        )
    print(f"Auto-selected POD model {best_name!r} (lowest NLL = {best_nll:.6g})", flush=True)
    return best_name


def plot_layer_sep_vs_strain(
    stacking: str,
    strains: np.ndarray,
    mean_sep: np.ndarray,
    std_sep: np.ndarray,
    dft_points: Sequence[StrainSepPoint],
    out_path: Path,
    *,
    dpi: int = 150,
) -> None:
    """Save mean interlayer separation ± std vs strain with DFT overlay."""
    fig, ax = plt.subplots(figsize=(7.0, 4.5))
    pct = 100.0 * np.asarray(strains, dtype=float)

    ax.plot(pct, mean_sep, label="ensemble mean", color="C0", zorder=2)
    ax.fill_between(
        pct,
        mean_sep - std_sep,
        mean_sep + std_sep,
        alpha=0.3,
        color="C0",
        label="ensemble std",
        zorder=1,
    )

    if dft_points:
        dft_x = 100.0 * np.asarray([p.dx for p in dft_points], dtype=float)
        dft_y = np.asarray([p.separation for p in dft_points], dtype=float)
        ax.plot(
            dft_x,
            dft_y,
            "o-",
            color="C2",
            label="DFT",
            zorder=3,
            markersize=6,
        )

    ax.set_xlabel(r"in-plane strain $\varepsilon_x$ (%)", fontdict=CSFONT)
    ax.set_ylabel("equilib. layer sep. (Å)", fontdict=CSFONT)
    ax.set_title(rf"$\nu_{{13}}$ — {stacking} stacking", fontdict=CSFONT)
    ax.legend(
        loc="upper left",
        prop={"family": CSFONT["fontname"], "size": 12},
        frameon=True,
    )
    ax.grid(True, alpha=0.25)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def plot_poisson_ratio_histogram(
    stacking: str,
    nu_samples: np.ndarray,
    dft_nu: float,
    out_path: Path,
    *,
    dpi: int = 150,
    n_bins: int = 30,
) -> None:
    """Histogram of ensemble Poisson ratios for one stacking, with DFT vertical line."""
    vals = np.asarray(nu_samples, dtype=float)
    vals = vals[np.isfinite(vals)]
    if vals.size == 0:
        print(f"    skip Poisson histogram for {stacking}: no finite samples", flush=True)
        return

    fig, ax = plt.subplots(figsize=(7.0, 4.5))
    ax.hist(
        vals,
        bins=n_bins,
        color="C0",
        alpha=0.75,
        edgecolor="white",
        linewidth=0.5,
        label="ensemble",
    )
    if np.isfinite(dft_nu):
        ax.axvline(
            float(dft_nu),
            color="C2",
            lw=2.5,
            linestyle="-",
            zorder=5,
            label="DFT",
        )

    ax.set_xlabel(r"$\nu_{13}$", fontdict=CSFONT)
    ax.set_ylabel("count", fontdict=CSFONT)
    ax.set_title(rf"$\nu_{{13}}$ — {stacking} stacking", fontdict=CSFONT)
    ax.legend(
        loc="upper left",
        prop={"family": CSFONT["fontname"], "size": 12},
        frameon=True,
    )
    ax.grid(True, alpha=0.25, axis="y")
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def plot_dft_energy_vs_separation(
    frames: Sequence[PoissonFrame],
    stacking: str,
    out_path: Path,
    *,
    dpi: int = 150,
) -> None:
    """
    DFT total energy vs interlayer separation with per-strain quadratic fits.

    Data points and fitted curves share a strain-level color map.  A separate
    line connects equilibrium ``(d_eq, E(d_eq))`` at each strain.
    """
    strains = _strain_values_for_stacking(frames, stacking)
    if strains.size == 0:
        return

    strain_pct = 100.0 * strains
    norm = Normalize(vmin=float(strain_pct.min()), vmax=float(strain_pct.max()))
    cmap = cm.get_cmap("viridis")

    fig, ax = plt.subplots(figsize=(8.0, 5.0))

    eq_seps: List[float] = []
    eq_energies: List[float] = []
    eq_strains: List[float] = []

    for target_dx in strains:
        block = _frames_at_strain(frames, stacking, float(target_dx))
        if not block:
            continue

        seps = np.array([f.separation for f in block], dtype=float)
        ens = np.array([f.dft_energy for f in block], dtype=float)
        color = cmap(norm(100.0 * float(target_dx)))

        ax.scatter(
            seps,
            ens,
            color=color,
            s=45,
            zorder=3,
            edgecolors="0.15",
            linewidths=0.5,
        )

        coeffs, d_eq, e_eq = fit_quadratic_energy_curve(seps, ens)
        if np.all(np.isfinite(coeffs)):
            d_line = np.linspace(float(seps.min()), float(seps.max()), 120)
            ax.plot(d_line, np.polyval(coeffs, d_line), color=color, lw=2.0, zorder=2)

        if np.isfinite(d_eq) and np.isfinite(e_eq):
            eq_seps.append(d_eq)
            eq_energies.append(e_eq)
            eq_strains.append(float(target_dx))

    if eq_seps:
        order = np.argsort(eq_strains)
        ax.plot(
            np.asarray(eq_seps, dtype=float)[order],
            np.asarray(eq_energies, dtype=float)[order],
            color="0.15",
            ls="--",
            lw=2.2,
            marker="o",
            markersize=7,
            mfc="white",
            mew=1.6,
            label=r"$d_\mathrm{eq}(\varepsilon)$ path",
            zorder=4,
        )

    sm = cm.ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array(strain_pct)
    cbar = fig.colorbar(sm, ax=ax, pad=0.02)
    cbar.set_label(r"in-plane strain $\varepsilon_x$ (%)")

    ax.set_xlabel("interlayer separation (Å)")
    ax.set_ylabel("total energy (eV)")
    ax.set_title(f"DFT — {stacking} stacking")
    ax.legend(loc="best")
    ax.grid(True, alpha=0.25)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def print_dft_equilibrium_separations(
    stacking: str,
    strains: np.ndarray,
    d_eq: np.ndarray,
) -> None:
    """Print DFT equilibrium interlayer separation at each in-plane strain."""
    strains = np.asarray(strains, dtype=float).ravel()
    d_eq = np.asarray(d_eq, dtype=float).ravel()
    print(f"  DFT {stacking} equilibrium separation vs strain:", flush=True)
    if strains.size == 0:
        print("    (no strain points)", flush=True)
        return
    for eps, d in zip(strains, d_eq):
        eps_pct = 100.0 * float(eps)
        if np.isfinite(d):
            print(f"    ε_x = {eps_pct:+.3f}%  d_eq = {d:.4f} Å", flush=True)
        else:
            print(f"    ε_x = {eps_pct:+.3f}%  d_eq = nan", flush=True)


def print_poisson_summary(
    dft_nu: Dict[str, float],
    model_nu: Dict[str, Dict[str, Tuple[float, float]]],
) -> None:
    """Print DFT and ensemble Poisson ratios (ν = −d(d_eq)/dε at ε = 0)."""
    print("\n=== Poisson ratio summary (ν = −d(d_eq)/dε at ε = 0) ===", flush=True)
    for stacking in STACKINGS:
        nu = float(dft_nu.get(stacking, float("nan")))
        if np.isfinite(nu):
            print(f"  DFT {stacking}:  ν = {nu:.4f}", flush=True)
        else:
            print(f"  DFT {stacking}:  ν = nan", flush=True)

    if not model_nu:
        return

    for model_name in sorted(model_nu):
        print(f"  {model_name}:", flush=True)
        for stacking in STACKINGS:
            mu, sig = model_nu[model_name].get(stacking, (float("nan"), float("nan")))
            if np.isfinite(mu) and np.isfinite(sig):
                print(f"    {stacking}:  ν = {mu:.4f} ± {sig:.4f}", flush=True)
            elif np.isfinite(mu):
                print(f"    {stacking}:  ν = {mu:.4f}", flush=True)
            else:
                print(f"    {stacking}:  ν = nan", flush=True)


def main() -> None:
    p = argparse.ArgumentParser(
        description=(
            "Plot equilibrium interlayer separation vs in-plane strain "
            "(quadratic E(d) fits on single-point DFT and model energies)."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    add_energy_models_arg(p, required=False)
    p.add_argument("--ensemble-dir", default=DEFAULT_ENSEMBLE_DIR)
    p.add_argument(
        "--temperature",
        type=float,
        default=None,
        help="MCMC temperature weight T for ensemble pickle (nearest match).",
    )
    p.add_argument(
        "--calibration-metrics-dir",
        default=DEFAULT_CALIBRATION_METRICS_DIR,
        help="Directory with calibration_*.npz from plot_bayes_factor.py --calculate.",
    )
    p.add_argument(
        "--calibration-target",
        default="energy",
        help="Target key in calibration npz (default: energy).",
    )
    p.add_argument(
        "--n-samples",
        type=int,
        default=DEFAULT_N_SAMPLES,
        help="Target number of successful ensemble evaluations per stacking.",
    )
    p.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_ENSEMBLE_SHUFFLE_SEED,
        help="RNG seed for ensemble shuffle.",
    )
    p.add_argument(
        "--figures-dir",
        type=Path,
        default=DEFAULT_FIGURES_DIR,
        help="Output directory for PNG figures (default: uncertainty_quantification/figures).",
    )
    p.add_argument(
        "--dft-xyz",
        type=Path,
        default=DEFAULT_DFT_XYZ,
        help=(
            "DFT single-point Poisson-ratio structures "
            "(default: data/blg_poisson_ratio_structures.xyz)."
        ),
    )
    p.add_argument(
        "--poly-degree",
        type=int,
        default=DEFAULT_POLY_DEGREE,
        help="Polynomial degree for ν = −d(d_eq)/dε at ε = 0 (default: 2).",
    )
    p.add_argument("--dpi", type=int, default=150)
    add_hyperparam_args(p)
    args, unknown = p.parse_known_args()
    cli_hyperparams = collect_workflow_hyperparams(args, unknown)

    os.chdir(UQ_DIR)

    dft_xyz = Path(args.dft_xyz)
    if not dft_xyz.is_absolute():
        dft_xyz = REPO_ROOT / dft_xyz if (REPO_ROOT / dft_xyz).exists() else UQ_DIR / dft_xyz

    figures_dir = Path(args.figures_dir)
    if not figures_dir.is_absolute():
        figures_dir = UQ_DIR / figures_dir
    figures_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading DFT structures from {dft_xyz}", flush=True)
    poisson_frames = load_poisson_frames(dft_xyz)
    if not poisson_frames:
        p.error(f"No AB/AA Poisson-ratio frames found in {dft_xyz}")

    dft_by_stack: Dict[str, List[StrainSepPoint]] = {}
    dft_nu: Dict[str, float] = {}
    for stacking in STACKINGS:
        strains, d_eq, points = dft_equilibrium_path(poisson_frames, stacking)
        dft_by_stack[stacking] = points
        dft_nu[stacking] = poisson_ratio_at_zero(strains, d_eq, args.poly_degree)
        print_dft_equilibrium_separations(stacking, strains, d_eq)

    for stacking in STACKINGS:
        pes_out = figures_dir / f"DFT_{stacking}_poisson_energy_vs_sep.png"
        plot_dft_energy_vs_separation(poisson_frames, stacking, pes_out, dpi=args.dpi)
        print(f"  Wrote {pes_out}", flush=True)

    if args.models:
        models = expand_model_patterns(args.models, args.ensemble_dir)
        if not models:
            p.error("No models matched --models patterns.")
    else:
        try:
            models = [
                select_pod_model_lowest_nll(
                    args.ensemble_dir,
                    args.calibration_metrics_dir,
                    calibration_target=args.calibration_target,
                )
            ]
        except ValueError as exc:
            p.error(str(exc))

    print(f"Models: {models}", flush=True)

    model_nu: Dict[str, Dict[str, Tuple[float, float]]] = {}

    for model_name in models:
        if not is_uq_energy_model(model_name):
            print(
                f"  skip {model_name!r}: unsupported UQ model",
                file=sys.stderr,
            )
            continue

        print(f"\n--- Model: {model_name} ---", flush=True)
        pkl_path, t_used = resolve_ensemble_pickle(
            model_name,
            args.ensemble_dir,
            args.temperature,
            calibration_metrics_dir=args.calibration_metrics_dir,
            calibration_target=args.calibration_target,
        )
        print(f"  Ensemble pickle: {pkl_path}  (T={t_used:g})", flush=True)

        ens_dict = load_ensemble_pickle(pkl_path)
        ensemble = np.asarray(ens_dict["ensemble"]["energy"], dtype=float)
        ensemble_shuffled = _shuffle_ensemble(ensemble, args.seed)
        print(
            f"  Shuffled ensemble (seed={args.seed}): {ensemble.shape[0]} members; "
            f"target {args.n_samples} successful per stacking",
            flush=True,
        )

        calc_obj, set_params_fn, load_name = build_uq_calculator(
            model_name, extra_kw=cli_hyperparams or None,
        )
        print(f"  Calculator: {load_name}", flush=True)

        model_nu[model_name] = {}

        for stacking in STACKINGS:
            print(f"  Stacking {stacking} …", flush=True)
            strains, mean_sep, std_sep, sep_ensemble, n_ok = evaluate_ensemble_vs_strain(
                calc_obj,
                ensemble_shuffled,
                args.n_samples,
                stacking,
                poisson_frames,
                set_params_fn=set_params_fn,
            )
            if n_ok == 0:
                print(f"    no successful ensemble members for {stacking}", file=sys.stderr)
                continue

            nu_samples = poisson_ratio_ensemble_samples(
                strains, sep_ensemble, args.poly_degree,
            )
            ok = np.isfinite(nu_samples)
            if np.any(ok):
                nu_mean = float(np.mean(nu_samples[ok]))
                nu_std = float(np.std(nu_samples[ok]))
            else:
                nu_mean, nu_std = float("nan"), float("nan")
            model_nu[model_name][stacking] = (nu_mean, nu_std)

            out_name = f"{model_name}_{stacking}_poisson_layer_sep.png"
            out_path = figures_dir / out_name
            plot_layer_sep_vs_strain(
                stacking,
                strains,
                mean_sep,
                std_sep,
                dft_by_stack.get(stacking, []),
                out_path,
                dpi=args.dpi,
            )
            print(f"    Wrote {out_path}  (n={n_ok})", flush=True)

            hist_name = f"{model_name}_{stacking}_poisson_ratio_histogram.png"
            hist_path = figures_dir / hist_name
            plot_poisson_ratio_histogram(
                stacking,
                nu_samples,
                dft_nu.get(stacking, float("nan")),
                hist_path,
                dpi=args.dpi,
            )
            print(f"    Wrote {hist_path}", flush=True)

        if hasattr(calc_obj, "close"):
            calc_obj.close()

    print_poisson_summary(dft_nu, model_nu)
    print("Done.", flush=True)


if __name__ == "__main__":
    main()
